  query filter($food_id: Int!) {
    foods(where: { id: { _eq: $food_id } }) {
      id
      title
      description
      category
      duration
      user {
        name
      }
      ingredients {
        id
        name
        amount
      }
      steps {
        id
        description
        step_number
      }
      comments {
        id
        user {
          name
        }
        comment
      }
      # likes{
      #   id
      # }
      rates {
        rate_user_id
        value
      }
      favorites {
        favorite_user_id
      }
      images {
        path
      }
      favorites {
        favorite_user_id
      }
    }
  }
