  query your_foods($user_id: Int!) {
    foods(where: { created_by: { _eq: $user_id } }) {
      id
      title
      description
      category
      duration
      user {
        name
      }
      images {
        path
      }
      likes_aggregate {
        aggregate {
          count
        }
      }
      favorites {
        favorite_user_id
      }
      likes(where: { like_user_id: { _eq: $user_id } }) {
        like_user_id
      }
    }
  }
